# Generated by Django 3.1.2 on 2020-10-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilot',
            old_name='race_count',
            new_name='races_count',
        ),
    ]
