# Generated by Django 3.1.2 on 2020-10-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_auto_20201015_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='has_it_completed',
            new_name='has_it_competed',
        ),
    ]
